package demo.model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 30 18:47:10 ART 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpByEmailImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmpByEmailImpl() {
    }
}

